Сделали вторую задачу
zedaster/PersonalFinanceBot pull request #29
Opened 2023-12-14 18:39 UTC by zedaster

2023-12-16 18:50 UTC, vpyzhyanov requested changes
Вы удивительно не ленивы в написании кода))

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/handler/command/budget/ListBudgetHandler.java
> +                    .replace("{real_expenses}", outputFormatter.formatDouble(realExpenses))
вроде не критичное замечание, но всё-таки мне не очень нравится такой способ заполнения параметров. Его недостаток в том, что после каждой такой команды создаётся новая строка. Тут аж 6 строк, хотя могли бы обойтись одной. Чем вас не устроил стандартный форматтер с использованием символа '`%s`'?

Получится что-то вроде такого:
```java
Message.BUDGET_LIST_ELEMENT.formatted(
        outputFormatter.formatRuMonthName(targetYearMonth.getMonth(),
        String.valueOf(targetYearMonth.getYear()),
        ...)
```

А константа:

```java
    public static final String BUDGET_LIST_ELEMENT = """
            %s %s:
            Ожидание: + %s | - %s
            Реальность: + %s | - %s""";
```

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/handler/command/budget/SingleBudgetHandler.java
> +                .replace("{expenses_left}", outputFormatter.formatDouble(expensesLeft))
а тут ещё больше

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/handler/command/budget/SingleBudgetHandler.java
> +        commandData.getBot().sendMessage(commandData.getUser(), Message.CURRENT_BUDGET
Нет смысла выносить константу в отдельный класс и делать публичной, если она используется только в одном классе, и тем более, в одном месте только. Определите все такие константы в том классе, где они реально используются.

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/message/Message.java
> +    public static final String INCORRECT_BUDGET_YEAR_MONTH = "Дата введена неверно! Введите ее в формате " +
Класс для констант - это не свалка для констант. Это место, где должны лежать **общие** константы, которые используются в нескольких разных классах. Очень многие эти константы **общими** не являются.

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/model/Budget.java
> +            case INCOME -> this.income = summary;
опять вы на тёмную сторону подались? Никакой логики в классе для данных быть не должно. Вся логика в обработчиках или сервисах. Тут просто геттеры и сеттеры, не нужно их объединять.

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/repository/budget/HibernateBudgetRepository.java
> +public class HibernateBudgetRepository implements BudgetRepository {
где JavaDoc?

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/repository/budget/HibernateBudgetRepository.java
> +     * Сохраняет бюджет в БД
А тут наоборот его быть не должно, он же написан в интерфейсе/родительском классе

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/service/ArgumentParseService.java
> +    public YearMonth parseYearMonth(String argument) throws DateTimeParseException {
это класс берёт на себя слишком много. Нужно его разделить, пусть на каждый объект будет отдельный класс. Одна задача - один класс. А то тут всё в свалку превращается. В один парсер можно только объединить параметры связанные со временем. Для чисел тоже можно объединять. Но остальные должны быть отдельными классами.

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/service/ArgumentParseService.java
> +            throw new NumberFormatException();
тут надо написать содержательное сообщение о том, что значение вышло за допустимые пределы и написать какие

2023-12-16 18:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/service/OutputFormatService.java
> +public class OutputFormatService {
По этому очень общему имени тоже можно понять, что его нужно разбить на несколько классов. Похоже на два, для чисел и для времени.

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/command/budget/CreateBudgetTests.java
> +                    String incomeAmount = (type == CategoryType.INCOME) ? wrongAmount : "100000";
этим циклом и условиями только усложняете тест. Если вы его разделите дублирования не будет, не переживайте

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/command/budget/CreateBudgetTests.java
> +        transactionManager.produceTransaction(session -> {
скажите мне пожалуйста, зачем вам транзакция, если вы всё равно в оперативной памятих храните данные с помощью фейкового репозитория?

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/repository/fake/FakeBudgetRepository.java
> +public class FakeBudgetRepository implements BudgetRepository {
Вот вам не лень ещё одну реализацию интерфейса для тестов писать. Лучше бы мокито использовали.

Впрочем я не понимаю, вы же говорили, что хотите БД в оперативной памяти поднимать. А сейчас не делаете этого. Вы уж определитесь

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/command/budget/EditBudgetTests.java
> +public class EditBudgetTests {
имя класса должно содержать слово Test в **единственном** числе

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/command/budget/SingleBudgetTests.java
> +        transactionManager.produceTransaction(session -> {
бессмысленная транзакция

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/command/budget/TestYearMonth.java
> +public class TestYearMonth {
Имя класса содержит слово Test, что говорит о том, что он содержит тесты. Но, о шок, он не содержит ни одного теста. Тогда всё существование этого класс очень сомнительно. Очень похоже на попытку повторить логику основного кода, что делать нельзя

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/repository/budget/TestBudgetRepository.java
> +        this.budgetRepository = new HibernateBudgetRepository();
удивительно, вы тестируете репозиторий на реальной базе, а обработчики команд на собственной реализации репозитория. Поражаюсь насколько вы не ленивые))) Можно было не делать никаких фейковых реализаций и не тестировать репозиторий отдельно, а проверить всё и сразу.

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/repository/budget/TestBudgetRepository.java
> +    private class TestArgumentContext {
класс сомнительного смысла и содержания. Опять попытка дублировать логику основного кода?

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/repository/empty/EmptyBudgetRepository.java
> +        throw new RuntimeException("Budget repository shouldn't be touched");
Используйте стандарт для таких случаев: `UnsupportedOperationException`

Ну не перестаю удивляться вашему нежеланию использовать Mockito, и отсутствию лени писать много кода.

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/repository/empty/EmptyCategoryRepository.java
> +        throw new RuntimeException("Category repository shouldn't be touched");
здесь везде аналогично

2023-12-16 18:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/repository/hibernate/TestHibernateBudgetRepository.java
> +public class TestHibernateBudgetRepository extends HibernateBudgetRepository {
Судя по содержимому этого класса его существование крайне сомнительно. И даже JavaDoc нет для того, чтобы понять зачем он был создан.

Имя класса снова содержит Test, но ни одного теста в нём нет. Это замечание относится ко всем классам в этом пакете.

2023-12-20 08:26 UTC, zedaster commented
Исправили все замечания

2023-12-20 19:50 UTC, vpyzhyanov requested changes
Задача принята. Как исправите последние замечания, можете мёрджить

2023-12-20 19:50 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/handler/FinanceBotHandler.java
> +    public FinanceBotHandler(UserRepository userRepository, OperationRepository operationRepository, CategoryRepository categoryRepository, BudgetRepository budgetRepository) {
рекомендую не увлекаться однострочным программированием, это не удобно, а написать параметры в несколько строк

2023-12-20 19:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/command/budget/CreateBudgetTests.java
> +                    String incomeAmount = (type == CategoryType.INCOME) ? wrongAmount : "100000";
Не исправлено!

2023-12-20 19:50 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/command/budget/ListBudgetTest.java
> +        this.operationRepository = Mockito.mock(OperationRepository.class);
выглядит это очень странно, один репозиторий вы замокали, а все остальные нет. Вы уж определитесь, либо вы мокаете, либо запускаете всё на тестовой базе.

2023-12-21 11:25 UTC, zedaster commented
Исправили последние замечания, делаем мердж.

2023-12-21 11:25 UTC, merged