Реализовал команду /avg_report
zedaster/PersonalFinanceBot pull request #35
Opened 2023-12-20 21:13 UTC by sxkxixx

2023-12-20 21:56 UTC, zedaster requested changes
Хорошо, но надо поправить

2023-12-20 21:56 UTC, zedaster commented on src/main/java/ru/naumen/personalfinancebot/handler/command/report/AverageReportHandler.java
> +        }
Вынести в DateParseService

2023-12-20 21:56 UTC, zedaster commented on src/main/java/ru/naumen/personalfinancebot/repository/operation/HibernateOperationRepository.java
> +                """;
Можно же просто дописать `and operations.category.user is null`

2023-12-20 21:56 UTC, zedaster commented on src/main/java/ru/naumen/personalfinancebot/service/ReportService.java
> +    private static final String AVG_REPORT_HEADER = "Подготовил отчет по стандартным категориям со всех пользователей за %s %s:\n";
`%o` для года

2023-12-20 21:56 UTC, zedaster commented on src/main/java/ru/naumen/personalfinancebot/service/ReportService.java
> +                String.valueOf(yearMonth.getYear())));
И под год можно поставить сразу `yearMonth.getYear()`

2023-12-20 21:56 UTC, zedaster commented on src/main/java/ru/naumen/personalfinancebot/service/ReportService.java
> +        }
Это лучше, чтобы репо давал null в там случае

2023-12-20 21:56 UTC, zedaster commented on src/test/java/ru/naumen/personalfinancebot/handler/command/report/AverageReportHandlerTest.java
> +    }
Проблема в том, что `getAverageSummaryByStandardCategory` тестами не покрыли, мы полностью управляем его состоянием. И так во всем классе. Надо обсудить и полагаю если начали везде интеграционки бахать, то ими и закончить проект.

2023-12-21 05:33 UTC, sxkxixx commented on src/main/java/ru/naumen/personalfinancebot/handler/command/report/AverageReportHandler.java
> +        }
Вынес же

2023-12-21 05:37 UTC, sxkxixx commented on src/main/java/ru/naumen/personalfinancebot/service/ReportService.java
> +    private static final String AVG_REPORT_HEADER = "Подготовил отчет по стандартным категориям со всех пользователей за %s %s:\n";
%o - представление числа в восьмеричном виде, точно ли нам надо переводить код в восьмеричную систему счисления?

2023-12-21 05:39 UTC, sxkxixx commented on src/main/java/ru/naumen/personalfinancebot/service/ReportService.java
> +    private static final String AVG_REPORT_HEADER = "Подготовил отчет по стандартным категориям со всех пользователей за %s %s:\n";
![image](https://github.com/zedaster/PersonalFinanceBot/assets/93007451/04ba7758-dcd0-4890-b886-d620f50cad7c)
Как раз из-за восьмеричной системы не проходит тест в EstimateReportTest.java

2023-12-21 07:06 UTC, zedaster commented on src/main/java/ru/naumen/personalfinancebot/service/ReportService.java
> +    private static final String AVG_REPORT_HEADER = "Подготовил отчет по стандартным категориям со всех пользователей за %s %s:\n";
Извиняюсь, там `%d`

2023-12-21 07:10 UTC, sxkxixx commented
@zedaster 
1. Добавил интеграционный тест AverageReportHandlerTest.java, для команды /avg_report (покрыл тестами запрос)
2. Исправил запрос к базе данных

На "%o" менять не стал, восьмеричная система вряд ли нужна

2023-12-21 07:13 UTC, sxkxixx commented
@zedaster 
Поменял %s на %d

2023-12-21 09:10 UTC, zedaster approved these changes
LGTM

2023-12-21 09:10 UTC, merged