Написали задачу 1. Pull Request на слияние с веткой main
zedaster/PersonalFinanceBot pull request #8
Opened 2023-11-18 16:31 UTC by sxkxixx

2023-11-30 18:52 UTC, zedaster commented on src/test/java/ru/naumen/personalfinancebot/handler/RemoveCategoryTests.java
> +    static {
В таком случае что при использовании `@AfterClass` в тесте?

2023-12-01 16:56 UTC, sxkxixx commented on src/main/java/ru/naumen/personalfinancebot/messages/StaticMessages.java
> +public class StaticMessages {
> 1. Нет JavaDoc
> 2. Слово Static можно убрать, оно лишнее (это детали реализации)

Нужен ли JavaDoc для каждой переменной в классе, если итак по значению константы понятно для чего она?

2023-12-05 18:32 UTC, sxkxixx commented
@vpyzhyanov 
Внес часть правок:

1. Добавил человекочитаемое исключение на случай, если бот не запустился.
2. Переименовал StaticMessages -> Messages и добавил JavaDoc к этому классу.
3. Убрал статичное исключение из класса AddOperationHandler, перенёс его в CategoryRepository.
4. Убрал "однострочное программирование" в методе SetBalanceHandler.beautifyDouble()
5. Переименовал все классы для тестов, убрал множественное число в названии классов.
6. Добавил JavaDoc там, где его не хватало
7. Переписал тесты для доабвлений операций: исправил ту самую критичную ошибку (Явное указание ожидаемого значения)

Оставшиеся правки:

1. Исправить работу с транзакциями.
2. Исправить static в тестах и критичные ошибки при указании ожидаемого значения

2023-12-10 09:44 UTC, zedaster commented
@vpyzhyanov Исправили замечания с предыдущей пары по первой задаче

2023-12-13 17:49 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/bot/Bot.java
> +    class PoolingException extends Exception {
Все классы должны быть в отдельных файлах. В этом случае использование вложенного класса неуместно.

Вложенный класс используется только тогда, когда он за пределы класса вообще не выходит.

2023-12-13 17:49 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/bot/Bot.java
> +        private final String exceptionMessage;
изобрели велосипед. Убирайте все поля и вызывайте конструктор родительского класса

2023-12-13 17:49 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/bot/TelegramBot.java
>      ) {
Скобки не принято переносить на следующую строку

2023-12-13 17:49 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/Main.java
> +        } catch (Bot.PoolingException exception) {
создание своего типа исключения тут не оправдано. Можно использовать общее. Впрочем особых проблем от этого нет.

2023-12-13 17:49 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/RemoveCategoryTests.java
> +    static {
Не использовать его

2023-12-13 18:04 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/repository/category/CategoryRepository.java
> +    class CategoryDoesNotExist extends Exception {
Все классы должны быть в отдельных файлах

2023-12-13 18:04 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/repository/category/HibernateCategoryRepository.java
> +public class HibernateCategoryRepository implements CategoryRepository {
где JavaDoc?

2023-12-13 18:04 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/messages/StaticMessages.java
> +public class StaticMessages {
**Константам** часто не нужен JavaDoc, т.к её имя должно полностью объяснять её назначение. В дополнение - можно.

**Полям** - как правило нужен. Только если не сильно очевидно, например `name`.

**Классам** - обязательно, даже если очевидно

2023-12-13 18:08 UTC, vpyzhyanov commented on src/test/java/ru/naumen/personalfinancebot/handler/OperationsTests.java
> +public class OperationsTests {
Не исправлено!

2023-12-13 18:11 UTC, vpyzhyanov requested changes
Есть замечания

2023-12-13 19:22 UTC, zedaster commented
Доправили часть замечаний, еще часть скоро будет

2023-12-13 20:03 UTC, sxkxixx commented
@vpyzhyanov 
Внесли все правки.

2023-12-14 05:21 UTC, vpyzhyanov requested changes
Как исправите оставшиеся маленькие замечания, можете мёрждить. Задача принята.

2023-12-14 05:21 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/repository/category/exception/CreatingExistingCategoryException.java
> + * Абстрация для иссключений, связанных с созданием категории, которая уже существует
Абстракция?

2023-12-14 05:21 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/repository/category/exceptions/CategoryDoesNotExistException.java
> +package ru.naumen.personalfinancebot.repository.category.exceptions;
чем это класс провинился, что вы его отселили в другой пакет?

Хотя само существование этого класс не оправдано. В нём тоже подменяется сообщение на имя класса.

Вы же могли просто создать CategoryException и везде использовать его с разными сообщениями. Но если очень хочется сделать много классов, то эти сообщения можно зашить внутрь конструтора.

2023-12-14 05:21 UTC, vpyzhyanov commented on src/main/java/ru/naumen/personalfinancebot/repository/category/exception/CreatingExistingCategoryException.java
> +    public String getCategoryName() {
метод не используется, как и поле. Они должны быть удалены.

Вы же могли просто создать CategoryException и везде использовать его с разными сообщениями. Но если очень хочется сделать много классов, то эти сообщения можно зашить внутрь конструктора. Впрочем как вы сделали в других классах.

2023-12-14 10:57 UTC, zedaster commented
Исправили замечания по исключениям, делаем merge.

2023-12-14 10:58 UTC, merged